info = {"message": "Rename label-studio/label_studio/annotation_templates/computer-vision/feotal_plans_deepEcho/config.yml to label-studio/label_studio/annotation_templates/computer-vision/feotal-plans-deepEcho/config.yml", "commit": "a3645b8a12d2f15923a838ff31086512debab152", "date": "2021-05-05 00:29:26 +0000", "branch": "main", "version": "a3645b8+dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
